# Generated by Django 4.2.8 on 2023-12-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
        migrations.AddField(
            model_name='carro',
            name='preco',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(verbose_name='Ano de Fabricação'),
        ),
    ]
